feat: 도서관 남은 좌석 UI 로직
KU-Stacks/KU-Ring-Android pull request #403
Opened 2024-12-24 15:01 UTC by boiledeggg

https://kuring.atlassian.net/browse/KURING-228?atlOrigin=eyJpIjoiYmUzY2VmZjNmOTIxNDk2ZmJjZmU3OWVkYTFmNTkxY2UiLCJwIjoiaiJ9

## 요약

- 도서관 공지탭에 잔여좌석 화면으로 이동하기 위한 배너 추가 : 5c605813a321e22dd7fb0757e290b20e37b07bd8
- 뷰모델 구현 및 레포지토리 연결 : 95b70500a21166870a6194b4bef708e4854e24c7
- 상허도서관앱 인텐트 추가 : c8b3284382f965b4ad7cc0aae37639efa0ced2a5

| 잔여좌석 UI | 상허도서관 이동 | 네트워크 오류 |
|:---:|:---:|:---:|
| <video src="https://github.com/user-attachments/assets/4c36c79e-e652-4cea-ac71-3a50c781e4e1" width="300"/> | <video src="https://github.com/user-attachments/assets/e9067878-db92-4e5c-9256-26fbf505158b" width="300"/> | <video src="https://github.com/user-attachments/assets/57be6f23-6421-4efd-86ec-41aff9dc0ef8" width="300"/> |

## 참고

- 도서관 앱 내 MainActivity가 없는 경우, 토스트 메시지를 띄우도록 자체적으로 처리했는데 이렇게 해도 될까요?
- 도서관 앱으로 이동하는 인텐트가 정상적으로 동작하려면 `Manifest`의 `<queries>` 에 도서관 앱 패키지명을 넣어야 하던데 이렇게 하는게 맞을까요?

2024-12-25 10:18 UTC, mwy3055 requested changes
* 도서관 앱이 깔려있지만 `MainActivity`가 없는 경우가 있을까요? 도서관 앱이 있거나 없거나 둘 중 하나일 것 같습니다. 
  * 도서관 앱이 있다면 지금처럼 앱을 열면 되고,
  * 도서관 앱이 없다면 지금처럼 플레이 스토어의 도서관 설치 페이지를 열면 됩니다. 
  * 결론: 이미 잘 구현하셨습니다. :+1:
* `Manifest`에 `<queries>`를 반드시 넣어야 하는지? 는 모르겠습니다. 적어도 제가 알기로는 그냥 intent에 패키지명 넣어서 검색하면 되는 걸로 알고 있는데, 이 부분은 석준님이 직접 확인해 보시는 게...? (정책이 바뀌었을 수도 있으니까요)

추가로 요청사항 몇 개 드립니다.

* 코드 포맷이 종종 깨지는 경우가 있습니다. 커밋할 때 자동으로 reformat하도록 설정해 두시면 편합니다.
* 세 번째 영상에서 네트워크가 없을 때 에러 텍스트를 보여주는데, 이미 로드한 데이터가 있는 경우에는 에러 텍스트는 보여주지 말고 토스트만 보여주면 될 것 같습니다. 
  * 데이터 최초 로드 and 네트워크 에러 → 에러 텍스트, 토스트 둘 다 보여주기
  * 데이터가 있는 상황 and 네트워크 에러 → 에러 토스트만 보여주기
* (이건 그냥 의견입니다) 프리뷰는 UI 자체가 바뀔 때만 바꾸셔도 됩니다. 왜 바꾸셨나 했더니 도서관 홈페이지에서 1/5열람실만 주고 있군요 ㅋㅋ

Request changes이긴 하지만 전반적으로 매우 잘 구현되었습니다. :+1: 드립니다. ㅎㅎ

2024-12-25 11:43 UTC, l2hyunwoo commented
> Manifest에 <queries>를 반드시 넣어야 하는지? 는 모르겠습니다. 적어도 제가 알기로는 그냥 intent에 패키지명 넣어서 검색하면 되는 걸로 알고 있는데, 이 부분은 석준님이 직접 확인해 보시는 게...? (정책이 바뀌었을 수도 있으니까요)

안 넣으면 터집니다... (경험담)

2024-12-25 11:48 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatActivity.kt
> +        }
에러시에 크래시틱스 로그남기는건 어떨까요?

2024-12-25 11:50 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatViewModel.kt
> +        get() = _uiState.asStateFlow()
```suggestion
    val uiState = _uiState.asStateFlow()
```

이건 get할 때마다 굳이 새로운 asStateFlow() 호출할 필요는 없을 것 같아요. 

+) asStateFlow와 ``val uiState: StateFlow<아무거나> = _uiState``
의 차이는 어떤 것이 있을까요?

2024-12-25 11:55 UTC, l2hyunwoo commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    )
혹시 isRefreshing이 트리거 되면서 리컴포지션이 수행될때 이 refreshState가 다시 업데이트 되면서 isRefreshing = true 부분이 두번 호출되지 않나요? 제가 `rememberPullRefreshState ` 내부 구현을 잘 몰라서 어떻게 될지 감이 안오네요

2024-12-25 11:56 UTC, l2hyunwoo commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    val notices = noticesFlow?.collectAsLazyPagingItems()
```suggestion
    val notices = viewModel.noticesFlow.collectAsLazyPagingItems()
```

이렇게 한줄로 줄일 수 있지 않을까요?

2024-12-25 11:56 UTC, l2hyunwoo commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    }
제가 알기로는 이게 다른화면으로 갔다가 다시 이 화면으로 돌아올때에 getNotices가 호출될 수도 있거든요. 혹시 이것도 의도된 동작일까요?

2024-12-25 11:57 UTC, l2hyunwoo commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/NoticeHorizontalPager.kt
> +                    shortCategoryName = NoticeScreenTabItem.values()[pageIndex].shortCategoryName,
```suggestion
                    shortCategoryName = NoticeScreenTabItem.entries[pageIndex].shortCategoryName,
```
로 바꾸라고 워닝뜨지 않았나요?

2024-12-25 11:58 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +}
이전에 만들었던거랑 중복되어서 사용하는 것 같은데 이러면 기존 베이스를 구현한 의도가 사라지지 않을까요

2024-12-25 11:58 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +                    items(seatStatus.rooms, key = { item -> item.name }) { status ->
key 설정 굳입니당

2024-12-25 11:59 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +    }
이것도 아까전에 달았던 리뷰와 마찬가지

2024-12-25 12:00 UTC, l2hyunwoo requested changes
일단 영상으로 봤을땐 괜찮은데 한번만 짚고 넘어가면 좋을 것들만 남겨놨어요

2024-12-25 12:00 UTC, mwy3055 commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/NoticeHorizontalPager.kt
> +                    shortCategoryName = NoticeScreenTabItem.values()[pageIndex].shortCategoryName,
네 근데 #404 에서 없어질 코드입니다

2024-12-26 01:11 UTC, mwy3055 commented
> > Manifest에 를 반드시 넣어야 하는지? 는 모르겠습니다. 적어도 제가 알기로는 그냥 intent에 패키지명 넣어서 검색하면 되는 걸로 알고 있는데, 이 부분은 석준님이 직접 확인해 보시는 게...? (정책이 바뀌었을 수도 있으니까요)
> 
> 안 넣으면 터집니다... (경험담)

업무에 큰 도움이 되었습니다. 감사합니다 (진짜임)

2024-12-29 17:43 UTC, boiledEgg-s commented on data/remote/src/main/java/com/ku_stacks/ku_ring/remote/library/LibraryService.kt
> +        @Query("branchGroupId") branchGroupId: Int,
제가 제대로 확인을 못한거였습니다,, 실제로 통신해서 테스트를 한게 아니라 json파일을 직접 집어넣어서 테스트를 하다보니 쿼리스트링에서 틀린걸 인지하지 못했네요ㅎㅎ

2024-12-29 17:44 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
>              fontFamily = SfProDisplay,
수정했습니다,,

2024-12-29 17:50 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatViewModel.kt
> +        get() = _uiState.asStateFlow()
`val uiState: StateFlow<...> = _uiState`의 경우 UI 단에서 MutableStateFlow로 타입캐스팅이 가능하지 않을까 추측해봅니다.

찾아보니까 `asStateFlow`는 ReadonlyStateFlow라는 읽기 전용 플로를 제공하여 편집이 불가능한 플로를 노출시킬 수 있다고 하네요!

2024-12-29 17:50 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatActivity.kt
> +        }
오 넣겠습니다!

2024-12-29 17:51 UTC, boiledEgg-s commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    )
사실 LibraryNoticeScreen은 기존 NoticeScreen 코드를 사용하여 세부적인 동작에 관해선 제대로 인지하진 못했습니다!
지적해주신 김에 알아봐야겠네요!

2025-01-03 10:13 UTC, boiledEgg-s commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    }
매번 새로 호출해야되지 않을까요? 돌아왔을 때 새로운 공지가 생겼을 수도 있으니까요.

2025-01-03 10:19 UTC, boiledEgg-s commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/compose/LibrarySeatScreen.kt
> +}
designsystem으로 뺐습니다!

2025-01-03 10:20 UTC, boiledEgg-s commented on feature/main/src/main/java/com/ku_stacks/ku_ring/main/notice/compose/inner_screen/LibraryNoticeScreen.kt
> +    val notices = noticesFlow?.collectAsLazyPagingItems()
`viewModel.noticesFlow`이 StateFlow 내부에 Flow를 포함하는 형태태여서 collect 후에 `.collectAsLazyPagingItem()` 적용이 가능한 것 같아요!

2025-01-03 17:43 UTC, boiledEgg-s commented
### 2025.01.03 수정사항

- `PagingLoadingIndicator`를 `designsystem/component/indicator`로 이동
- 건국대 도서관 앱 `PackageManager.NameNotFoundException`에 대한 crashlytics 메시지 추가

2025-01-08 12:39 UTC, mwy3055 commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatViewModel.kt
> +        get() = _uiState.asStateFlow()
이거 저한테도 알려주셨던 거 ㅋㅋ

2025-01-08 13:00 UTC, mwy3055 approved these changes
저는 괜찮아 보입니다

2025-01-12 07:44 UTC, l2hyunwoo approved these changes

2025-01-12 07:44 UTC, l2hyunwoo commented on feature/library/src/main/java/com/ku_stacks/ku_ring/library/LibrarySeatViewModel.kt
> +        updateIsLoading( true)
```suggestion
        updateIsLoading(true)
```

2025-02-05 13:49 UTC, mwy3055 approved these changes

2025-02-05 13:54 UTC, merged